### PR TITLE
feat: update to Meteor 1.10.2

### PR DESCRIPTION
**Pull request by aldeed**
## Changes
Update to Meteor 1.10.2 with Node 12.16.1 and version 3.5.7 of the `mongodb` library. This resolves potential vulnerabilities in NPM dependencies.

## Testing
1. Run `make dev-reaction-admin` to test the development build (happy path testing on admin UI).
2. Stop the admin service and delete the `docker-compose.override.yml` symlink.
3. Build production image with `docker build . -t reactioncommerce/admin:3.0.0-beta.local`
4. Temporarily update the image in `docker-compose.yml` to be `reactioncommerce/admin:3.0.0-beta.local`
5. Run `docker-compose up -d` and then verify that the admin UI works (happy path testing).

### CODE REVIEW

**Review by willopez — CHANGES_REQUESTED** [review]
Works well for most of the happy path. However, I did find that uploaded images don't render, I see this error `Refused to load the image 'http://localhost:3000/assets/files/Media/862TwhAYykdonCAk5/thumbnail/black_boot.png' because it violates the following Content Security Policy directive: "img-src data: 'self'` @manueldelreal can you verify you see the same. And @aldeed seems like this might be an issue that was introduced by this update.

**Comment by manueldelreal** [comment]
> Works well for most of the happy path. However, I did find that uploaded images don't render, I see this error `Refused to load the image 'http://localhost:3000/assets/files/Media/862TwhAYykdonCAk5/thumbnail/black_boot.png' because it violates the following Content Security Policy directive: "img-src data: 'self'` @manueldelreal can you verify you see the same. And @aldeed seems like this might be an issue that was introduced by this update.

Same results for me locally, I checked against acme with the latest beta tag being reviewed and I don't see that issue.

**Comment by aldeed** [comment]
@willopez @manueldelreal Is it possible you have `NODE_ENV=production` (or anything other than "development") in your `.env`? That's the only way I can reproduce what you're seeing. The server allows `http` and `localhost` images only when `NODE_ENV` is `development`. This didn't change since the previous release, but maybe Meteor was previously overriding it to be `development` and now is not? I don't see any mention of that in their release notes, but it's possible.

**Comment by aldeed** [comment]
I added `NODE_ENV=development` to the example `.env` to hopefully mitigate this. People will still need to manually update their `.env` file, but that's recommended to check with every new release anyway.

**Comment by manueldelreal** [comment]
I didn't have `NODE_ENV` set on my `.env` file, I explicitly set it to `development` and as you said @aldeed the images are rendered now.

**Review by manueldelreal — APPROVED** [review]
:shipit:

**Review by willopez — APPROVED** [review]
Looks good now.

**Pull request merged**
