### PR TITLE
fix:make-init-dev not working

### LINKED ISSUE #281: Make init-dev command in reaction-development-platform doesn't work
## Issue Description
I'm trying to setting up the environment development but the admin container get down after 2 minutes and the log of the container says:

Failed to reset plugins file at /usr/local/src/app/client/plugins.js (image below)
image

The other containers looks good.

Thanks in advance.

## Steps to Reproduce
1. git clone git@github.com:reactioncommerce/reaction-development-platform.git
2. cd reaction-development-platform
3. make init-dev

### Versions
3.7.1

### PR DESCRIPTION
**Pull request by m5ingh**
Resolves #281 
Impact: none or minor (not sure)
Type: bugfix

## Issue

make init-dev command was failing for reaction-admin because of permission issues. same [issue](https://github.com/reactioncommerce/reaction-development-platform/issues/54) plagued other moc projects which was solved there but was never implemented in reaction-admin.

## Solution

solution was to add fix-up and entry-point scripts to the reaction admin project and call the same from docker-dev file. 

## Breaking changes

no other changes made besides adding entry-point and vol fix-up scripts and changing some commands in dockerdev file.

## Testing

remove existing reaction-admin from moc dev platform
add this repo in its place
make init-dev-reaction-admin
should initialize reaction in dev mode even on machine where it was failing previously

### CODE REVIEW

**Comment by Akarshit** [comment]
Is there someone(on whose machine the this was failing before) who can test this, please...

**Comment by m5ingh** [comment]
i'll ask in issues thread if anyone can take a look

**Comment by delagroove** [comment]
@MohanNarayana can you test this?

**Comment by delagroove** [comment]
we haven't been able to recreate this. Closing for now.

**Pull request closed without merging**
