### PR TITLE
fix: remove `canInviteToGroup` helper on the client

### LINKED ISSUE #211: Accounts screen is blank and throws error after shop creation
## Issue Description
After creating your first user, if you click on "Accounts" the screen is blank and it throws this error in the console:

```
TypeError: Cannot read property 'ixKfbghjg9tYLX9BZ' of undefined
    at Object.canInviteToGroup (5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959)
    at 5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959
    at Array.filter (<anonymous>)
    at Reaction(GroupsTableCell) (5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959)
```

## Steps to Reproduce
1. Fresh clone of platform and start
1. Create your first account/shop
1. Click on "Accounts"

### Versions
`release-3.0.0-beta.3` Hash: `cee2161c6`

### PR DESCRIPTION
**Pull request by kieckhafer**
Resolves #211 
Impact: **minor**
Type: **bugfix**

## Issue Description

> After creating your first user, if you click on "Accounts" the screen is blank and it throws this error in the console:
> 
> ```
> TypeError: Cannot read property 'ixKfbghjg9tYLX9BZ' of undefined
>     at Object.canInviteToGroup (5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959)
>     at 5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959
>     at Array.filter (<anonymous>)
>     at Reaction(GroupsTableCell) (5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959)
> ```

## Solution
Remove the UI / client helper `canInviteToGroup`. This helper was checking permissions in a way we no longer support in `v3.0.0`.

This solution relies on the API's server side permissions checks to determine if a user has the correct permissions to perform an action. The client can be updated in the future to provide a pre-action warning / error / restriction, if desired.

## Breaking changes
Any custom code that uses `Reaction.canInviteToGroup` helper will need to be updated tor remove that helper.

## Testing
1. Create an account and a shop
1. See that you can view the `Accounts` page.
1. See that you can invite a user when you are an admin / have the correct permissions
1. See that you get a server error when you are not an admin / don't have the correct permissions

### CODE REVIEW

**Comment by kieckhafer** [comment]
@mikemurray @willopez see the discussion in #211 as to whether this is the appropriate fix.

**Review by willopez — CHANGES_REQUESTED** [review]
Starting with a fresh db and registering a new user and creating a shop and then I click on the accounts menu item and get this error: 
```
main.js:178 Uncaught TypeError: Cannot read property 'some' of undefined
    at roleCheck (main.js:178)
    at Object.hasPermission (main.js:216)
    at Object.hasAdminAccess (main.js:263)
    at hoc.js:91
    at tracker.js:40
    at Computation._compute (tracker.js:308)
    at new Computation (tracker.js:206)
    at Object.Tracker.autorun (tracker.js:576)
    at tracker.js:38
    at Object.Tracker.nonreactive (tracker.js:603)```

**Comment by kieckhafer** [comment]
@willopez I think that's the same issue you were seeing [in this ticket](https://github.com/reactioncommerce/reaction-admin/issues/203). Does it work if you refresh? If so, lets keep that a separate issue.

**Comment by willopez** [comment]
Yes, refreshing it "fixes" the issue. @aldeed was going to look at a way to refresh the user, any updates on this Eric?

**Comment by aldeed** [comment]
@willopez No but I agree that's a separate issue that should not hold back this PR

**Review by willopez — APPROVED** [review]
LGTM

**Pull request merged**
