### PR TITLE
Update to Meteor 2.3, React 17 and react-sortable-tree 2.8.0

### PR DESCRIPTION
**Pull request by loan-laux**
Signed-off-by: Loan Laux <loan@outgrow.io>

Impact: **minor**
Type: **chore**

## Issue
Meteor, React and `react-sortable-tree` (which we're currently fighting with on the Navigation page) were all slightly outdated. This PR updates them.

## Breaking changes
None, since Meteor 2.3 and React 17 don't have breaking changes AFAIK.

## Testing
Try every page, make sure nothing breaks.

### CODE REVIEW

**Comment by Akarshit** [comment]
@MohanNarayana Can you do the testing of this one. I think you already have the context for these updates.

**Comment by MohanNarayana** [comment]
@Akarshit I'll review this, thanks.

**Review by MohanNarayana — APPROVED** [review]
Looks good. Thanks.

**Review by MohanNarayana — APPROVED** [review]

**Pull request merged**
