### PR TITLE
Add full GQL support to product editor

### LINKED ISSUE #168: [v3.0.0] Cannot upload images to product
## Issue Description
Attempting to upload a product image to a newly created product results in a toast error being displayed on the client.
The photo upload is not completed.

```
tus: invalid or missing Location header, originated from request (response code: 200, response text: <!DOCTYPE html> <html> <head> <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/7e17d3a8ef1ab6da8dcc1d2d32c486a81fc99229.css?meteor_css_resource=true"> <meta name="fragment" content="!"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <noscript><div style="padding: 40px; font-size: 200%; text-align: center;">This site requires JavaScript. Please enable it in your browser settings.</div></noscript> <script type="text/javascript">window.prerenderReady = false;</script> </head> <body> <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.8.1%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%22graphQlApiUrlHttp%22%3A%22http%3A%2F%2Flocalhost%3A3000%2Fgraphql-beta%22%2C%22graphQlApiUrlWebSocket%22%3A%22ws%3A%2F%2Flocalhost%3A3000%2Fgraphql-beta%22%2C%22i18nBaseUrl%22%3A%22http%3A%2F%2Flocalhost%3A3000%22%2C%22storefrontHomeUrl%22%3A%22http%3A%2F%2Flocalhost%3A4000%22%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A4080%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22autoupdate%22%3A%7B%22versions%22%3A%7B%22web.browser%22%3A%7B%22version%22%3A%223281211b848ca1619b029b6868f699628387deb3%22%2C%22versionRefreshable%22%3A%22663664386d50393657884e0bd20b493af34e0494%22%2C%22versionNonRefreshable%22%3A%22b3d25dee4f6f922c0e10b3e4068d4e06c3f5a822%22%7D%2C%22web.browser.legacy%22%3A%7B%22version%22%3A%227c702afb1e738ab6f277af83aea6a573c414aa74%22%2C%22versionRefreshable%22%3A%22663664386d50393657884e0bd20b493af34e0494%22%2C%22versionNonRefreshable%22%3A%22819dccba656d9afc5fa23dc5b30d835a05e88905%22%7D%7D%2C%22autoupdateVersion%22%3Anull%2C%22autoupdateVersionRefreshable%22%3Anull%2C%22autoupdateVersionCordova%22%3Anull%2C%22appId%22%3A%2216fc7k11cajtkx5sgjml%22%7D%2C%22appId%22%3A%2216fc7k11cajtkx5sgjml%22%2C%22isModern%22%3Atrue%7D"))</script> <script type="text/javascript" src="/c11a11308b42e2e13031df6b3b3e1d6bfc2bacf9.js?meteor_js_resource=true"></script> </body> </html>)
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Fresh install of Reaction via Reaction Platform
2. Ensure that reaction-admin is running
3. Create account and first shop
4. Create product
5. Attempt to upload a product image
6. Observe error

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
release-3.0

### LINKED ISSUE #184: [v.3.0.0] Full GQL coverage on product editor
There are various issues with the product editor that make it a poor experience. The main cause of this is the use of Meteor and GQL simultaneously for editing which causes sluggish controls and incorrect data display.

In this refactor

- Update to use only GQL, no meteor.
- Update components to use Component Library / Catalyst (current components may rely too much on meteor)

Related Tickets:
https://github.com/reactioncommerce/reaction-admin/issues/68
https://github.com/reactioncommerce/reaction-admin/issues/169

### PR DESCRIPTION
**Pull request by mikemurray**
Resolves #168 #184 #212 #216 #220 #223
Impact: **major**  
Type: **feature|refactor**

## Issue

There are many issues with the current meteor specific implementation of the product admin.

## Solution

- Fix all of those problems and convert it to GraphQL
- Removed the template field (it's not available in the API in 3.0)
- Removed the google plus message field from the social for.

## Breaking changes

none.

## Testing

1. Use api with this PR: https://github.com/reactioncommerce/reaction/pull/6141
1. Use the admin and make sure everything works in the product editor

(non-critical issues can go into a list and I can address them in another PR.)

### CODE REVIEW

**Comment by janus-reith** [comment]
@mikemurray Which ToDos are still open here?
What I noticed so far:
- API only resolves top-level media and doesn't check for variant Id, variant has no media resolver. Therefore, variant media is empty and the product media includes all product and variant images.
-Product Fragment queries fields shouldAppearInSitemap and taxDescription which are not on product.
- Catalog plugin could be removed entirely and Publish Controls from there moved over to product admin. Also, this still used composeWithTracker and needs to be rewritten aswell to make use of the `useProduct` hook.

**Comment by loan-laux** [comment]
+1 @janus-reith. If there's anything we (the community) can pick up and finish, don't hesitate @mikemurray. I know many people are eagerly waiting for this to be finished as the product editor doesn't work right now.

**Comment by janus-reith** [comment]
@loan-laux Totally aggree, would be great to have this done. Also, from my experience this new implementation is way better to work with due to the use of hooks. Therefore it probably is more straightforward to finish this up than to patch the old implementation together to work again.

@mikemurray Some further quick notes on things i had to do to get this working for me:
The Product-/Variant Mediaform doesn't reflect the current state when new Images are added or old ones removed.
I added `refetchProduct` to the list of items desctructured from `useProduct`, and pass it to `ProductMediaGallery`
In the `handleRemoveMedia` function there I await `archiveMediaRecord`, then call `refetchProduct`, pretty simple.
But adding them is a bit tricky.
In `ProductMediaGallery` I created a function `handleMediaAdded` and pass that as a prop to `MediaUploader`, which calls it after the upload finished.
The catch here is, that this is not a synchronous process as sharp converts the images after the upload, and the refetched Product would contain a new media entry, but with all URLs as `null`.

As we have no proper way of knowing the exact time and polling the product query will probably be a separate concern, for now I simply do `await new Promise(resolve => setTimeout(resolve, 5000))` before calling `refetchProduct` in my `handleMediaAdded` function in order to give the API enough time to deal with the new image.
(There might still be cases where 5 Seconds might not be enough, but waiting too long deteriorates the UX.

**Comment by mikemurray** [comment]
@janus-reith When in doubt, set timeout 😄. We might be able to poll every few seconds after a successful upload until we get a non-null media item.

**Comment by mikemurray** [comment]
@willopez Ok... This is enough for this PR. The editor still needs some work, especially to the media gallery block, but for the most part, everything is in place and seems to work. I'd like to push any non-critical feedback into a fresh PR.

One issue, in particular, would be with the Media Gallery editor. I've put those issues into this ticket: https://github.com/reactioncommerce/reaction-admin/issues/236

**Comment by janus-reith** [comment]
@mikemurray It would be great to port over the publishControls Component aswell by removing it from the separate obsolete catalog plugin and moving it into the Product Admin, and then removing the composeWithTracker part to have a truly meteor-free solution.

**Comment by janus-reith** [comment]
@mikemurray When changes are saved and the updated Product is returned, `publishedProductHash` and `currentProductHash` are the same, so the Publish button won't become active.

After a page reload the changes are visible, ot by doing a second change in order to get a new refetch. That state would be old again:
I could take a published Product with Title "ABC 123", change it to "ABC 1234", Publish button greyed out. Then change it back to "ABC 123", and the Publish button becomes active.

Might need api changes to correctly deliver a new hash directly upon change, or else, an artifical delay like for images.
**Update**: I just figured out that simply adding another `refetchProduct` inside `onUpdateProduct` does the trick for now without another artifical delay here.
However, that still is not a clean solution, as the Payload of `updateProduct` is expected to have all the fresh Product data, therefore not requiering a manual refetch.

**Comment by janus-reith** [comment]
The TagSelector Component needs `overflow-y: visible` in order to display a List of Tags properly, else it would be cut of at the Dialog height.
The issue is noticable when having 3 or more Tags to choose from.

As this is broken in the catalyst library, one option is to define a custom theme override in the admin's theme:
`
MuiDialog: {
      paper: {
        overflowY: "visible"
      }
    } 
`

Certainly better to fix this in catalyst.

**Comment by mikemurray** [comment]
@janus-reith 
**Product hash:** Yea, I've seen that happen sometimes. We probably need to look at the API to see why the hash isn't delivered with the result on time. It might be doing the has async with an app event or something.

**MUI Dialog**: I agree, probably best to fix the default in Catalyst.

**Comment by mikemurray** [comment]
@janus-reith Just checked, and yes, the `hasProduct` function runs on an the app events `afterProductUpdate` and `afterVariantUpdate`. So just like the media, we're going to have to figure out a solution to this async stuff.

**Comment by willopez** [comment]
I am adding non-critical issues to another issue here: https://github.com/reactioncommerce/reaction-admin/issues/237. Other than those issues noted in #237 this is a good foundation to build on.

**Review by willopez — APPROVED** [review]
Approving so that we can merge this and start fixing issues on new PRs. The issues found are in issue #237.

**Pull request merged**
