### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by loan-laux**
Impact: **major**
Type: **performance|refactor|chore**

## Issue
There's a lot of dead code, mainly comprised of unused components, HOCs and pages.

I know that `reaction-admin` will soon be phased out, but to me it looks like we're still a couple of months away from this happening. I could be wrong, but still, to me it seems that such a clean-up would be welcome to the people and companies who are using `reaction-admin` on a daily basis.

## Solution
This PR removes all of the dead code I could find. Some may have slipped through the cracks, but I believe this will already be a very welcome clean-up.

My methodology with this PR can be described in a single GIF:

Flamethrower

Hence, there's a possibility I could have removed some things that weren't supposed to be removed. I've taken all the precautionary measures I could (test all features, do global searches for usage, etc), but you never know. Testing all kinds of obscure, hidden and forgotten features would be very much appreciated to make sure everything works as it should.

## Breaking changes
Not sure but it doesn't appear so. Would appreciate feedback.

## Testing
1. Test every page and every feature. Sorry for not being very specific here but I don't know what else to write.

### CODE REVIEW

**Comment by loan-laux** [comment]
@willopez @chrispotter I can't request reviews from you guys, but feel free to assign yourselves and look through the changes when you get a chance.

**Comment by balibebas** [comment]
Pulled down the outgrow topic branch for testing and dev-linked it locally. The build went well when I restarted my services but I admin is hanging on connection attempts so I switched back to `beta.9` for now. Would be nice to enjoy some of this dead code elimination as it could help inform what feature parity looks like for https://github.com/reactioncommerce/admin-core

**Comment by loan-laux** [comment]
Thanks for the feedback @balibebas. Is it hanging on connection attempts to the DB? Or to the GQL API? Haven't seen that happen on my end, but it's a major issue indeed if it's caused by these changes.

**Comment by ghost** [comment]
> Thanks for the feedback @balibebas. Is it hanging on connection attempts to the DB? Or to the GQL API? Haven't seen that happen on my end, but it's a major issue indeed if it's caused by these changes.

You're too quick. Right after I wrote that I tried with beta 9 and see it's unrelated to this branch. :D Will let you know when I get it up and running if I can before moving on.

**Comment by ghost** [comment]
Tested by building an image as I wasn't able to get the dev link working for this repo. Imported a fresh MongoDB and performed DB migrations. Then registered a user and tested the following:

- [x] Updating store information (email, name)
- [x] Adding a test products
- [x] Adding discounts
- [x] Adding tags and tag image
- [x] Updating site navigation
- [x] Inviting a store owner
- [x] Creating a new invitee group
- [x] Inviting user to new group
- [x] Enabling a payment method
- [x] Creating a fulfillment method
- [x] Enabling a custom API plugin
- [x] Updating shop localization
- [x] Adding tax information
- [x] Creating an order
- [x] Updating fulfillment group
- [x] Viewing order changes via storefront
- [x] Capturing an order payment
- [x] Adding a tracking number
- [x] Confirming tracking number updated storefront

Didn't encounter any errors and everything looks at parity with the existing `beta.9` (and `beta.7` save for Accounts).

**Review by willopez — APPROVED** [review]
Thanks this much needed clean up! I tested the app and everything seems ok.

**Pull request merged**
