### PR TITLE
fix: show product not found in products table

### LINKED ISSUE #162: Product table is hidden when no products are found
## Issue Description

Products table is hidden when no products are found, or when filtering by product ids.

Screen Shot 2019-08-14 at 10 49 58 AM

## Steps to Reproduce
1. Create .csv file with one column like so
```
_id
12345
```
2. In the products table select filter by file under actions
3. Upload the .
csv, and filter
4. See the table hidden

OR

Just delete all your products via the UI or in the mongo DB

## Possible Solution

Don't hide the table/card, instead show a message saying "no results were found" in the table.

### PR DESCRIPTION
**Pull request by trojanh**
Signed-off-by: trojanh <rajan.tiwari@kiprosh.com>

Resolves https://github.com/reactioncommerce/reaction-admin/issues/162  
Impact: **minor**  
Type: **bugfix**

## Issue
Do not hide the products table if no products are present instead show `no products found`.

## Solution
image

### CODE REVIEW

**Comment by aldeed** [comment]
Thanks @trojanh ! Assigned @mikemurray to review when he's back from vacation. It looks fine to me, but Mike will know whether this is the correct way to show the empty table. (We'll hopefully be replacing all tables with the Catalyst table soon anyway.)

**Comment by trojanh** [comment]
I had seen this [React-Table ](https://github.com//reactioncommerce/reaction-admin/blob/8b9c10fd786c0428f11a45510c2495833ddcb7d9/imports/plugins/core/tags/client/components/TagDataTable.js#L19)usage but I focused on fixing the issue for now as I was not sure if that was the accepted approach. 

[Catalyst table](https://catalyst.reactioncommerce.com/#/Components/Content/DataTable) looks great, would love help with that @aldeed .

**Comment by janus-reith** [comment]
`products.js` here has an import which is not present anymore:
`import { getTagIds as getIds } from "/lib/selectors/tags";`

**Review by mikemurray — CHANGES_REQUESTED** [review]
One minor change. Can you make the height of the `textNotFound` cell 50px? This will give grey background has some vertical space around the text, and make it look more like the rows when the table has data.

**Comment by willopez** [comment]
@trojanh please update this branch by merging in the latest `trunk`

**Comment by trojanh** [comment]
@mikemurray @willopez I have made the requested changes. Sorry for the delay. 

@janus-reith it seems that was already handled on `trunk` by some other PR.

**Review by aldeed — APPROVED** [review]

**Pull request merged**
